# Generated by Django 4.1.7 on 2023-04-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='fullname',
            new_name='Fullname',
        ),
    ]
